/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/area/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 지역 정보 등록 */
        post: operations["addAreas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/trading-volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 지역 별 거래량 */
        get: operations["getTradingVolumeByRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/avg-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 지역 별 평균 값 */
        get: operations["getAvgPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/avg-price/per-area": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 지역 별 평당 가격 */
        get: operations["getAvgPriceByRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/avg-price/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 지역 별 평균가 증감률 */
        get: operations["getAvgPriceChangedByRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/avg-price/build-age": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 지역 별 신축/준신축/구축 평균가 */
        get: operations["getAvgPriceByBuildAge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deal/collected/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 수집 된 년도, 반기 목록 */
        get: operations["collectedPeriodList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deal/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 반기 별 데이터 저장 */
        get: operations["fetch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Empty: Record<string, never>;
        RsDataEmpty: {
            resultCode: string;
            /** Format: int32 */
            statusCode: number;
            msg: string;
            data: components["schemas"]["Empty"];
            success: boolean;
            fail: boolean;
        };
        RegionCountDto: {
            region?: string;
            /** Format: int64 */
            count?: number;
        };
        RsDataListRegionCountDto: {
            resultCode: string;
            /** Format: int32 */
            statusCode: number;
            msg: string;
            data: components["schemas"]["RegionCountDto"][];
            success: boolean;
            fail: boolean;
        };
        AvgPriceDto: {
            region?: string;
            /** Format: double */
            avgPrice?: number;
        };
        RsDataListAvgPriceDto: {
            resultCode: string;
            /** Format: int32 */
            statusCode: number;
            msg: string;
            data: components["schemas"]["AvgPriceDto"][];
            success: boolean;
            fail: boolean;
        };
        AvgPricePerAreaDto: {
            region?: string;
            /** Format: double */
            avgPricePerArea?: number;
        };
        RsDataListAvgPricePerAreaDto: {
            resultCode: string;
            /** Format: int32 */
            statusCode: number;
            msg: string;
            data: components["schemas"]["AvgPricePerAreaDto"][];
            success: boolean;
            fail: boolean;
        };
        RegionPriceChangeDto: {
            region?: string;
            /** Format: double */
            prevAvgPrice?: number;
            /** Format: double */
            currAvgPrice?: number;
            /** Format: double */
            changeRate?: number;
        };
        RsDataListRegionPriceChangeDto: {
            resultCode: string;
            /** Format: int32 */
            statusCode: number;
            msg: string;
            data: components["schemas"]["RegionPriceChangeDto"][];
            success: boolean;
            fail: boolean;
        };
        RegionBuildAgeAvgPriceDto: {
            region?: string;
            /** Format: double */
            newAvgPrice?: number;
            /** Format: double */
            semiNewAvgPrice?: number;
            /** Format: double */
            oldAvgPrice?: number;
        };
        RsDataListRegionBuildAgeAvgPriceDto: {
            resultCode: string;
            /** Format: int32 */
            statusCode: number;
            msg: string;
            data: components["schemas"]["RegionBuildAgeAvgPriceDto"][];
            success: boolean;
            fail: boolean;
        };
        CollectedPeriodDto: {
            /** Format: int32 */
            statYear?: number;
            statHalf?: string;
            propertyType?: string;
        };
        RsDataListCollectedPeriodDto: {
            resultCode: string;
            /** Format: int32 */
            statusCode: number;
            msg: string;
            data: components["schemas"]["CollectedPeriodDto"][];
            success: boolean;
            fail: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    addAreas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
    getTradingVolumeByRegion: {
        parameters: {
            query: {
                statYear: number;
                statHalf: string;
                propertyType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListRegionCountDto"];
                };
            };
        };
    };
    getAvgPrice: {
        parameters: {
            query: {
                statYear: number;
                statHalf: string;
                propertyType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListAvgPriceDto"];
                };
            };
        };
    };
    getAvgPriceByRegion: {
        parameters: {
            query: {
                statYear: number;
                statHalf: string;
                propertyType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListAvgPricePerAreaDto"];
                };
            };
        };
    };
    getAvgPriceChangedByRegion: {
        parameters: {
            query: {
                currYear: number;
                currHalf: string;
                propertyType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListRegionPriceChangeDto"];
                };
            };
        };
    };
    getAvgPriceByBuildAge: {
        parameters: {
            query: {
                statYear: number;
                statHalf: string;
                propertyType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListRegionBuildAgeAvgPriceDto"];
                };
            };
        };
    };
    collectedPeriodList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataListCollectedPeriodDto"];
                };
            };
        };
    };
    fetch: {
        parameters: {
            query: {
                collectedYear: number;
                collectedHalf: string;
                propertyType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RsDataEmpty"];
                };
            };
        };
    };
}
